create table curso (
    id bigint not null generated by default as identity,
    nome varchar(255) not null,
    categoria varchar(50) not null,
    data_criacao timestamp not null,
    primary key (id)
);

insert into Curso(id,nome,categoria, data_criacao) values (1, 'primeiro curso', 'programacao', current_timestamp);
