create table usuario (
    id bigint not null generated by default as identity,
    nome varchar(255) not null,
    email varchar(255) not null,
    data_criacao timestamp not null,
    primary key (id)
);

insert into Usuario(id, nome, email, data_criacao) values (1, 'primeiro usuario', 'primeiro@email.com', current_timestamp);
