create table resposta (
    id bigint not null generated by default as identity,
    mensagem varchar(255) not null,
    autor_id bigint not null,
    topico_id bigint not null,
    solucao boolean not null,
    data_criacao timestamp not null,
    primary key (id),
    foreign key(autor_id) references usuario(id),
    foreign key(topico_id) references topico(id)
);

